name: Build (tag and pull_request) and publish (tag)

on:
  push:
    tags:        
      - v*.*.*
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose up
    - name: Show dir
      run: ls
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: executables
        path: |
          **.AppImage
          
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v2
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/*.AppImage
