on:
  push:
    branches:
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - name: Install git-lfs
      run: dnf update -y && dnf install -y git-lfs
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: toolbxtuner.flatpak
        manifest-path: build-aux/org.kuchelmeister.ToolbxTuner.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
    - name: ls
      run: ls
