on:
  push:
    branches:
      - main
  pull_request:

name: build-and-prerelease

jobs:
  flatpak-release-target:
    name: build-flatpak-release-target
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: toolboxtuner-release.flatpak
        manifest-path: build-aux/org.kuchelmeister.ToolboxTuner.json
        run-tests: true
        cache-key: flatpak-builder-release-${{ github.sha }}
        upload-artifact: false
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak-release
        path: |
          *.flatpak
  flatpak-screenshot-target:
    name: build-flatpak-screenshot-target
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: toolboxtuner-screenshot.flatpak
        manifest-path: build-aux/org.kuchelmeister.ToolboxTuner.Screenshot.json
        run-tests: true
        cache-key: flatpak-builder-screenshot-${{ github.sha }}
        upload-artifact: false
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak-screenshot
        path: |
          *.flatpak
  flatpak-dev-target:
    name: build-flatpak-dev-target
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: toolboxtuner-dev.flatpak
        manifest-path: build-aux/org.kuchelmeister.ToolboxTuner.Devel.json
        run-tests: true
        cache-key: flatpak-builder-dev-${{ github.sha }}
        upload-artifact: false
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak-dev
        path: |
          *.flatpak
  vendor:
    name: vendor-prerelease
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: dtolnay/rust-toolchain@stable
    - run: ./build-aux/dist-vendor.sh dist . && tar czf vendor.tar.gz dist
    - run:  sha256sum vendor.tar.gz > vendor.tar.gz.sha256sum
    - uses: actions/upload-artifact@v4
      with:
        name: vendor
        path: |
          *.tar.gz
          *.sha256sum
  publish-prerelease:
    name: publish-prerelease
    needs: [flatpak-dev-target, vendor]
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'main') && github.ref_type == 'branch'
    steps:
    - uses: actions/download-artifact@v4
    - name: Show files
      run: ls -R
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: dev
        title: 'Latest Development Build'
        files: |
          **/*-dev.flatpak
          **/*.tar.gz
          **/*.sha256sum


