---
name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+.0-9]+.0-9]+"

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: toolboxtuner.flatpak
        manifest-path: build-aux/org.kuchelmeister.ToolboxTuner.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
        upload-artifact: false
    - uses: actions/upload-artifact@v4
      with:
        path: |
          *.flatpak
  vendor:
    name: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - run: ./build-aux/dist-vendor.sh dist . && tar czf vendor.tar.gz dist
    - run:  sha256sum vendor.tar.gz > vendor.tar.gz.sha256sum
    - uses: actions/upload-artifact@v4
      with:
        path: |
          *.tar.gz
          *.sha256sum
  publish-prerelease:
    needs: [flatpak, vendor]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Show files
      run: ls -R
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/*.flatpak
          **/*.tar.gz
          **/*.sha256sum

